Rails:
  Enabled: true

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 10

Style/ClassVars:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
