development:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_development?') %>

test:
  adapter: postgresql
  database: travis_ci_test

production:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_production?') %>
