development:
  environment: development
  username: devuser
  password: devpass
  url: 127.0.0.1
  port: 3001
  request_time_gap_min: 1
test:
  environment: test
  username: testuser
  password: testpass
  url: 127.0.0.1
  port: 3001
  request_time_gap_min: 0.05
production:
  environment: production
  username: produser
  password: prodpass
  url: 127.0.0.1
  port: 3001
  request_time_gap_min: 60
