development:
  environment: development
  username: devuser
  password: devpass
  url: localhost
  port: 3001
  request_time_gap_min: 1
  stream_link: localhost/icecast.ogg
  icecast:
    web_addr: http://localhost:8000
    selector: /mountpoint
  webchat:
    server: my.irc.server
    channel: '#somechan'
    nick_prefix: lp
test:
  environment: test
  username: testuser
  password: testpass
  url: localhost
  port: 3001
  request_time_gap_min: 0.05
  stream_link: localhost/icecast.ogg
  icecast:
    web_addr: http://localhost:8000
    selector: /mountpoint
  webchat:
    server: my.irc.server
    channel: '#somechan'
    nick_prefix: lp
production:
  environment: production
  username: produser
  password: prodpass
  url: localhost
  port: 3001
  request_time_gap_min: 60
  stream_link: localhost/icecast.ogg
  icecast:
    web_addr: http://localhost:8000
    selector: /mountpoint
  webchat:
    server: my.irc.server
    channel: '#somechan'
    nick_prefix: lp
